### ISSUE TITLE
Android crashes when many contacts has icons with "FAILED BINDER TRANSACTION"

### ISSUE THREAD

**Issue by kaminskypavel** [rt2zz/react-native-contacts#106]
11-01 21:36:44.807 28640-29350/vc.aleph.karma E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 252)
11-01 21:36:44.808 28640-29350/vc.aleph.karma E/ContactsProvider: Error writing contact image to file:
                                                                  java.io.FileNotFoundException: Failed opening content provider: content://com.android.contacts/contacts/679/photo
                                                                      at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1143)
                                                                      at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
                                                                      at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
                                                                      at com.rt2zz.reactnativecontacts.ContactsProvider.getPhotoURIFromContactURI(ContactsProvider.java:215)
                                                                      **at com.rt2zz.reactnativecontacts.ContactsProvider.loadContactsFrom(ContactsProvider.java:149)
                                                                      at com.rt2zz.reactnativecontacts.ContactsProvider.getContacts(ContactsProvider.java:92)
                                                                      at com.rt2zz.reactnativecontacts.ContactsManager.getAll(ContactsManager.java:42)
                                                                      at java.lang.reflect.Method.invoke(Native Method)**
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by npomfret** [comment]
You stack trace doesn't match up with the code.  Are you using an old version?

**Comment by kaminskypavel** [comment]
I was getting this with 0.50 and then with 0.51

**Comment by npomfret** [comment]
Can you try with master?  and post the stack trace from there?

**Comment by morenoh149** [comment]
@kaminskypavel @npomfret actually I just bumped the version on npm to 0.5.2 you can grab it from there if you want just delete the folder in `node_modules` and reinstall.

**Comment by npomfret** [comment]
I just need a stack trace that lines up with the code in master.  The one you posted was from an earlier version so I can't use it to diagnose whats going on.

**Comment by kaminskypavel** [comment]
I'll try with the master and report back

**Comment by kaminskypavel** [comment]
just checked with master , looks like it [did the trick](https://github.com/rt2zz/react-native-contacts/commit/7c2345dac963aabacf40b519792faec55d77744a)
