### ISSUE TITLE
app crash with java.lang.SecurityException on getAll

### ISSUE THREAD

**Issue by YUSHEN2015** [rt2zz/react-native-contacts#313]
**log:**

java.lang.SecurityException: Proxy package com.android.providers.contacts from uid 10005 or calling package ** from uid 10128 not allowed to perform READ_CONTACTS
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:532)
	at android.content.ContentResolver.query(ContentResolver.java:473)
	at com.rt2zz.reactnativecontacts.b.a(ContactsProvider.java:113)
	at com.rt2zz.reactnativecontacts.ContactsManager$1.run(ContactsManager.java:79)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

**device info:**

android 7.1.2 (25)，xiaomi:MI 5X:arm64-v8a
android 6.0.1 (23)，Xiaomi:MI NOTE LTE:armeabi-v7a
android 4.4.4 (19)，samsung:SM-T560:armeabi-v7a

**version:**

"react-native-contacts": "^2.1.3"

I got this error on some device above，and this issue cannot be reproduced on any other deivce, eg. Nexus 5 android 6.0.1

**Comment by morenoh149** [comment]
That is a permissions error message. Doublecheck you are requesting the permissions https://github.com/rt2zz/react-native-contacts/#android-permissions

**Comment by YUSHEN2015** [comment]
@morenoh149 
Thanks，I had added READ_CONTACTS permission，and this issue can only be reproduced on very few device，and cannot be reproduced 100%.
btw, my project targetSdkVersion is 22.

**Comment by morenoh149** [comment]
if you are properly requesting the permissions then the only other thing I can imagine is that those phones have added restrictions, the error clearly states the app has not been given the read_contacts permission. Doublecheck in your code that the app has the correct permission before attempting getAll, I know this will be difficult unless you have one of those phones for testing.

**Comment by felansu** [comment]
same error here @morenoh149, with sdk version 22

**Comment by morenoh149** [comment]
this is a permission issue. The error says so `Proxy package com.android.providers.contacts from uid 10005 or calling package ** from uid 10128 not allowed to perform READ_CONTACTS` doublecheck permissions are granted. https://github.com/rt2zz/react-native-contacts#permissions

**Comment by felansu** [comment]
WHAT!? 👎

**Comment by morenoh149** [comment]
if you share your code and help reproduce we can reopen the request. Double check instructions for api < 23 https://github.com/rt2zz/react-native-contacts#api-22-and-below
