### ISSUE TITLE
安卓 权限检测报错

### ISSUE THREAD

**Issue by kmlidc** [rt2zz/react-native-contacts#323]
Redmi Note 4X android 7.0

java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{fc6f588 16179:com.hiwoniu.weiling/u0a211} (pid=16179, uid=10211) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4256)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5651)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2281)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1531)
	at android.content.ContentResolver.query(ContentResolver.java:516)
	at android.content.ContentResolver.query(ContentResolver.java:473)
	at com.rt2zz.reactnativecontacts.ContactsProvider.getContacts(ContactsProvider.java:170)
	at com.rt2zz.reactnativecontacts.ContactsManager$1.run(ContactsManager.java:88)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

**Comment by morenoh149** [comment]
please follow https://github.com/rt2zz/react-native-contacts#android-permissions specifically `from ProcessRecord{fc6f588 16179:com.hiwoniu.weiling/u0a211} (pid=16179, uid=10211) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS`

**Comment by JslinSir** [comment]
@morenoh149  How are Chinese characters sorted?   Android  getAll()   api

**Comment by JslinSir** [comment]
[#328](https://github.com/rt2zz/react-native-contacts/issues/328)

**Comment by dahudson88** [comment]
Actually found this....to fix it...

 https://medium.com/react-native-development/fixing-problems-in-react-native-caused-by-new-permission-model-on-android-1e547f754b8

**Comment by morenoh149** [comment]
@dahudson88 did you follow https://github.com/rt2zz/react-native-contacts#android-1 ?

**Comment by morenoh149** [comment]
Need to request permissions. Study readme. https://github.com/rt2zz/react-native-contacts#android-permissions and https://github.com/rt2zz/react-native-contacts#permissions
