### ISSUE TITLE
Unable to open database file (code 14)

### ISSUE THREAD

**Issue by BigPun86** [rt2zz/react-native-contacts#42]
![screenshot_2016-03-10-19-07-30](https://cloud.githubusercontent.com/assets/7880624/13679307/6e468be4-e6f3-11e5-9ab3-3289b9878b91.png)

Not sure if this is an issue accorded to this module. But this error occurs everytime i use getAll - Contacts. Any ideas?

Stacktrace: 
    
    ContactsManager.java line 46
    com.rt2zz.reactnativecontacts.ContactsManager.getAll

	Fatal Exception: android.database.sqlite.SQLiteException: unable to open database file (code 14)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:505)
	at android.content.ContentResolver.query(ContentResolver.java:440)
	at com.rt2zz.reactnativecontacts.ContactsManager.getAll(ContactsManager.java:46)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:249)
	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:428)
	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(NativeRunnableDeprecated.java)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:211)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
	at java.lang.Thread.run(Thread.java:818)

**Comment by morenoh149** [comment]
what version are your running? of react native and this module.

I ran into this ages [ago](https://github.com/rt2zz/react-native-contacts/issues/19) and was fixed [here](https://github.com/rt2zz/react-native-contacts/commit/d0ebd3230abd57087798f89a049299e989012ed9)

**Comment by BigPun86** [comment]
RN v0.20 and contacts "react-native-contacts": "^0.1.5"

**Comment by BigPun86** [comment]
Sorry for disturbing :D thanks @morenoh149

**Comment by BigPun86** [comment]
just installed wih npm i --save react-native-contacts@latest and it gave me 0.2.1

**Comment by rt2zz** [comment]
hah, you guys are fast. I *just* published 0.2.2 since there were a couple of outstanding bug fixes in there.

**Comment by morenoh149** [comment]
I'm assuming it worked
